version: '3'
services:
  backend:
    build:
      context: /home/ubuntu/thesis_deployment/python_backend_api
      dockerfile: Dockerfile
    container_name: sur-backend
    image: sur-backend
    ports:
      - "8000:8000"
    networks:
      - thesis_deployment_frontend_backend_connection
    volumes:
      - "/home/ubuntu/thesis_deployment/python_backend_api/:/api"

  frontend:
    build:
      context: /home/ubuntu/thesis_deployment/react_frontend_ui
      dockerfile: Dockerfile
    container_name: sur-frontend
    image: sur-frontend
    ports:
      - "3000:80"
    networks:
      - thesis_deployment_frontend_backend_connection
    volumes:
      - "/home/ubuntu/thesis_deployment/react_frontend_ui/:/app"
      - "sur_node_vol:/app/node_modules"

networks:
  thesis_deployment_frontend_backend_connection:
volumes:
  sur_node_vol: